const projects = [
  { src: "/BED11.jpeg", category: "Halls", title: "Warmth in every detail", location: "Interiors / Room" },
  { src: "/BED22.jpeg", category: "Halls", title: "A quiet sense of luxury", location: "Interiors / Room" },
  { src: "/BED33.jpeg", category: "Halls", title: "Comfort, thoughtfully designed", location: "Interiors / Room" },
  { src: "/HALL11.jpeg", category: "Halls", title: "An inviting first impression", location: "Interiors / Hall" },

  { src: "/bar1.jpeg", category: "Bar Spaces", title: "A space with character", location: "Bar Spaces / Interior" },
  { src: "/BAR22.jpeg", category: "Bar Spaces", title: "Details that set the mood", location: "Bar Spaces / Display" },
  { src: "/BAR33.jpeg", category: "Bar Spaces", title: "Designed to stand out", location: "Bar Spaces / Display" },
  { src: "/BAR44.jpeg", category: "Bar Spaces", title: "Warm light, rich textures", location: "Bar Spaces / Interior" },
  { src: "/BAR55.jpeg", category: "Bar Spaces", title: "A striking display", location: "Bar Spaces / Interior" },

  { src: cafeArches.url, category: "Cafés", title: "A room with a point of view", location: "Dolci / Interior" },
  { src: gymWindows.url, category: "Gyms", title: "Energy, made visible", location: "Fitness / Training floor" },
  { src: hallWindows.url, category: "Halls", title: "Light finds its rhythm", location: "Events / Main hall" },
  { src: barWarm.url, category: "Bar Spaces", title: "After hours, elevated", location: "Hospitality / Bar" },
  { src: cafePendant.url, category: "Cafés", title: "Details worth lingering over", location: "Dolci / Dining" },
  { src: gymOrange.url, category: "Gyms", title: "A new kind of momentum", location: "Fitness / Strength" },
  { src: hallLight.url, category: "Halls", title: "Gathering, with intention", location: "Events / Dining hall" },
  { src: barCounter.url, category: "Bar Spaces", title: "The conversation starts here", location: "Hospitality / Counter" },
  { src: cafeLounge.url, category: "Cafés", title: "Soft edges, strong identity", location: "Dolci / Lounge" },
  { src: gymCardio.url, category: "Gyms", title: "A brighter way to train", location: "Fitness / Cardio" },
  { src: barLounge.url, category: "Bar Spaces", title: "Mood after dark", location: "Hospitality / Lounge" },
  { src: cafeNight.url, category: "Cafés", title: "A landmark after sunset", location: "Dolci / Exterior" },

  { src: hallGrand1.url, category: "Halls", title: "Scale, softly framed", location: "Events / Main hall" },
  { src: hallGrand2.url, category: "Halls", title: "A stage for every gathering", location: "Events / Banquet" },
  { src: hallGrand3.url, category: "Halls", title: "Volume, with warmth", location: "Events / Celebration hall" },
  { src: hallGrand4.url, category: "Halls", title: "Designed for the long table", location: "Events / Dining" },
  { src: hallGrand5.url, category: "Halls", title: "Ceremony in every corner", location: "Events / Reception" },
  { src: hallGrand6.url, category: "Halls", title: "Where the room holds its breath", location: "Events / Grand hall" },
  { src: hallGrand7.url, category: "Halls", title: "A canvas for occasions", location: "Events / Hall" },

  { src: cafeStorefront.url, category: "Cafés", title: "First impressions, in blue", location: "Dolci / Storefront" },
  { src: cafeTerrace.url, category: "Cafés", title: "Indoor calm, outdoor light", location: "Dolci / Terrace" },
  { src: cafeFacade.url, category: "Cafés", title: "A façade that invites", location: "Dolci / Street front" },
  { src: cafeShelves.url, category: "Cafés", title: "Display as architecture", location: "Dolci / Retail wall" },
  { src: cafeCart.url, category: "Cafés", title: "Craft on wheels", location: "Dolci / Display cart" },
  { src: cafeMural.url, category: "Cafés", title: "A wall that tells a story", location: "Dolci / Mural" },
  { src: cafeDisplay.url, category: "Cafés", title: "The counter, centre stage", location: "Dolci / Pastry counter" },
  { src: cafeCartWall.url, category: "Cafés", title: "Texture, arch, and light", location: "Dolci / Feature wall" },
  { src: cafeDoor.url, category: "Cafés", title: "Details at the threshold", location: "Dolci / Entry detail" },
  { src: cafeCounter.url, category: "Cafés", title: "Curves that welcome", location: "Dolci / Service counter" },
];
